### ISSUE TITLE
Are there any osx-arm64 build or noarch build?

### ISSUE THREAD

**Issue by david-tao-as01** [conda-forge/cartopy-feedstock#108]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Here's a m1 mbp user asking
for no useable package on osx-arm64 system

**Comment by xylar** [comment]
@david-tao-as01, at least one thing holding back an osx-arm64 build is that we're having trouble getting shapely built for osx-arm64:
https://github.com/conda-forge/shapely-feedstock/pull/81

**Comment by xylar** [comment]
Another related discussion:
https://github.com/SciTools/cartopy/issues/1687

**Comment by xylar** [comment]
closed via #111
