### ISSUE TITLE
Can't conda update to or install to Cartopy 0.20.0

### ISSUE THREAD

**Issue by xaviernogueira** [conda-forge/cartopy-feedstock#124]
I installed cartopy yestarday to my env but it yesterday and only today realized that it did not install the newest versions (0.18.0 is installed, not 0.20.0). This appears to cause issues w/ cfeatures as described on this other thread (#1849) due to the change in servers.

If I try to update it, it says it is up to date.
When I uninstall it, then force install 0.20.0 w/ the conda command below, it gets stuck forever at "Solving environment" after first successfully collecting package metatdata, but then failing with initial frozen solve. I attached a screenshot of such an attempt.

Code to reproduce
conda install -c conda-forge cartopy=0.20.0
OR
conda update cartopy (which updates it to 0.18.0 not the most recent version)

I have also tried "conda config --set channel_priority strict" before, and installing via PyCharms Package manager. The same problem persists. 

Would really like some help here. I cannot do my job until I have access cfeature, which when using 0.18.0 are no longer retrievable from the url.

Thanks
Xavier
![cartopyerror](https://user-images.githubusercontent.com/58796351/136238630-37263be6-f21e-447f-a7dd-548a3152f374.png)

**Comment by xylar** [comment]
@xaviernogueira, yeah, it would be great if upgrading just worked but sometimes the solver can't figure it out and there's not really an alternative we can offer to creating a new environment.  That's largely an issue beyond this feedstock and even beyond conda-forge.

I'm going to close this issue for now but feel free to re-open if you would like to provide a full set of details on your environment you're hoping to upgrade.  We might be able to help you figure out what the sticking point is.
