### ISSUE TITLE
regro-cf-autotick-bot erroring with `v0.22` update

### ISSUE THREAD

**Issue by trexfeathers** [conda-forge/cartopy-feedstock#155]
### Comment:

I know you've all been working hard on release automation 🤩, so I just wanted to make you aware that the PyPI-to-conda automation isn't currently working.

Cartopy appears in the [conda-forge version updates list](https://conda-forge.org/status/#version_updates) under the `Errored` heading, with this text:

```
2.00 attempts - The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '0.22.0' to make sure they exist!

We also found the following errors:

 - could not hash URL template 'https://pypi.io/packages/source/C/Cartopy/Cartopy-{{ version }}.tar.gz'
```

**Comment by xylar** [comment]
Caropy developers didn't include a `.tar.gz` file with the latest PyPI release:
https://pypi.org/project/Cartopy/#files

**Comment by xylar** [comment]
This means we will have to switch to getting source from GitHub, which is not ideal but not that big a deal.

**Comment by ocefpaf** [comment]
They moved to publishing wheels upstream, maybe they forgot to add the sdist? @trexfeathers can you confirm of that is the case? While we can move to GitHub it would be nice to keep publishing the sdist on PyPI too.

**Comment by xylar** [comment]
I already made an issue: https://github.com/SciTools/cartopy/issues/2228
