### ISSUE TITLE
Offline version of cartopy

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cartopy-feedstock#27]
@willirath commented on [Sun Feb 05 2017](https://github.com/conda-forge/conda-forge.github.io/issues/328)

(I'd be happy to provide a PR myself.)

## Problem

Cartopy provides a very limited set of feature data (shapefiles et al.) and downloads features to the user cache whenever they are needed.  This is usually a good practice, but interferes with people working without permanent internet access (seagoing oceanographers, people in large data-centers who are trapped behind firewalls, someone working on a plane, etc.).

## Proposed solution

Create a feedstock which downloads all features upon installation.

To download all features, use (on python2.7)
```bash
feature_download.py \
    --output ${CONDA_PREFIX}/lib/python2.7/site-packages/cartopy/data physical \
    gshhs cultural cultural-extra
```
with [feature_download.py](https://github.com/SciTools/cartopy/blob/master/tools/feature_download.py) from the cartopy repo.

##  Caveats

Make sure to make use of conda's hard linking across virtual environments?

---

@jakirkham commented on [Sun Feb 05 2017](https://github.com/conda-forge/conda-forge.github.io/issues/328#issuecomment-277537925)

For future reference, discussion of changes to an individual package should be conducted on the issue tracker of that feedstock. In this case, the [cartopy feedstock]( https://github.com/conda-forge/cartopy-feedstock ) would be the right place. Am moving this issue over to that feedstock. Please discuss more over there.

**Comment by xylar** [comment]
@willirath, this is a great idea.  I have also run into this problem several times.

 I presume we would want to create a second, optional conda package that contains the data, say `cartopy-data`?

Also, there doesn't seem to be a way to set an environment variable that cartopy recognizes to point to the path for the downloaded data.  Given that the default location is outside of a conda environment, this could be a problem.  I need to look into this a bit more so I can provide more details.

**Comment by willirath** [comment]
I've solved this problem for me using https://git.geomar.de/open-source/cartopy_offlinedata

It has most of the logic needed for building a conda-forge package containing the data.

And there _is_ a mechanism for overriding standard configs in cartopy: <https://github.com/SciTools/cartopy/blob/9114626b429627a90c6ed65684e72f4d4384fce7/lib/cartopy/__init__.py#L40>

So from my PoV, creating a `cartopy-data` package boils down to:
- [ ] Check if it's allowed to redistributed the  https://naciscdn.org data.
- [ ] Use https://github.com/SciTools/cartopy/blob/master/tools/feature_download.py to download a full copy of the data when the package is built. (See <https://git.geomar.de/open-source/cartopy_offlinedata/blob/23ea474df8b70b65b68032a0074cab2c5289f922/bin/download_cartopy_data.sh> for a bash script already doing this.)
- [ ] Ensure that `cartopy_userconfig.update_config` is importable and sets the path to the data. (Preferable to do this via an env var?)

I don't really have time to do this myself. But if you want to give it a shot, I'd chime in whenever necessary.

**Comment by xylar** [comment]
Thanks so very much for the instructions.  I hadn't realized there was this this mechanism for creating a `cartopy_userconfig` (documentation remains sparse), and that is just the ticket!

> Check if it's allowed to redistributed the https://naciscdn.org data.

This link makes is quite clear that redistribution won't be a problem: http://www.naturalearthdata.com/about/terms-of-use/

I have a little time so I'll see if I can get this going today.

**Comment by xylar** [comment]
@willirath, I've made some progress.  Before I get too far, I wondered if:
* you are willing to accept a pull request to the https://git.geomar.de/open-source/cartopy_offlinedata repo (and if this is possible)?
* whether the changes on the following branch (which I'm happy to explain if needed) would be acceptable to you: https://github.com/xylar/cartopy_offline_data/tree/add_license
* whether you would be willing to make a 0.2.0 release once these changes are merged?

Unfortunately, I can't make a conda-forge package from your repo unless there is a license file and an official release.

**Comment by xylar** [comment]
Here is the draft recipe on `staged-recipes`, awaiting a release of `cartopy_offlinedata` from @willirath:
https://github.com/xylar/staged-recipes/tree/cartopy_offlinedata/recipes/cartopy_offlinedata

**Comment by willirath** [comment]
@xylar Thanks a lot! I've moved this to Github and invited you as a collaborator.

**Comment by willirath** [comment]
:tada: https://github.com/conda-forge/cartopy_offlinedata-feedstock
