### ISSUE TITLE
Remove matplotlib < 2.0 pin

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/cartopy-feedstock#28]
Can we re-examine the pinning against matplotlib < 2.0? As far as I can tell, the library isn't fundamentally broken with matplotlib. Based on SciTools/Cartopy#773, the only changes needed are to a ticker and to make sure linewidth is set properly. I'm willing to make a patch for conda-forge  for these changes if that helps.

My issue is that in a month I'm teaching a workshop:
1. I will not teach new users matplotlib < 2.0 only to have them turn around and adjust in 6 months
2. CartoPy 0.15.x fixes several bugs I've encountered teaching this very workshop, so using the 0.14.x means I'm walking in with a release with known problems (while the fixes exist in a released version)
3. On conda-forge, dropping back to 0.14.3 also forces me to use numpy 1.11, which means *everything* is using numpy 1.11 (though this hasn't **YET** caused a problem)
4. I'd really like to not have to explain to new users why we need to use two different channels for packages--the whole point of having conda-forge is so we have one community place.

**Comment by ocefpaf** [comment]
> I'm willing to make a patch for conda-forge for these changes if that helps.

Yes please! I will merge https://github.com/conda-forge/cartopy-feedstock/pull/29 quick so you can work on the patch.
