### ISSUE TITLE
html

### ISSUE THREAD

**Issue by datfinhon** [conda-forge/cartopy-feedstock#31]
<A href="https://www.quantifiedcode.com/app/project/15e2d9208d9740f680ecd896ba0d4d45"> <img src = "https://www.quantifiedcode.com/api/v1/project/15e2d9208d9740f680ecd896ba0d4d45/badge.svg" alt = "Vấn đề mã" /> </A>

**Comment by datfinhon** [comment]
markdown
[! [Mã vấn đề] (https://www.quantifiedcode.com/api/v1/project/15e2d9208d9740f680ecd896ba0d4d45/badge.svg)] (https://www.quantifiedcode.com/app/project/15e2d9208d9740f680ecd896ba0d4d45)

**Comment by ocefpaf** [comment]
Spam? Closing this...
