### ISSUE TITLE
Packaging bug in cartopy=0.14.3=np110py27_3 ?

### ISSUE THREAD

**Issue by megies** [conda-forge/cartopy-feedstock#32]
Could it be there's a packaging bug in `cartopy` version `0.14.3` build `np110py27_3`?

We're running into an error in CI, [on Travis OSX exclusively](https://travis-ci.org/obspy/obspy/jobs/216730989#L2425):
```
ERROR: test_location_plot_ortho (obspy.core.tests.test_network.NetworkCartopyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/obspy/core/tests/test_network.py", line 348, in test_location_plot_ortho
    color='yellow', label=False, outfile=ic.name)
  File "/Users/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/obspy/core/inventory/network.py", line 489, in plot
    from obspy.imaging.maps import plot_map
  File "/Users/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/obspy/imaging/maps.py", line 44, in <module>
    import cartopy.crs as ccrs
  File "/Users/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/cartopy/__init__.py", line 110, in <module>
    import cartopy.crs
  File "/Users/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/cartopy/crs.py", line 37, in <module>
    import cartopy.trace
ImportError: dlopen(/Users/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/cartopy/trace.so, 2): Library not loaded: @rpath/libgeos_c.1.dylib
  Referenced from: /Users/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/cartopy/trace.so
  Reason: Incompatible library version: trace.so requires version 10.0.0 or later, but libgeos_c.1.dylib provides version 9.0.0
```

[Installed versions are](https://travis-ci.org/obspy/obspy/jobs/216730989#L1635):
```
cartopy                   0.14.3              np110py27_3    conda-forge
geos                      3.3.3                         0
```

[In CI we first install main dependencies with fixed versions](https://travis-ci.org/obspy/obspy/jobs/216730989#L1341) and after that [install optional dependencies with `--no-update-dependencies` option](https://travis-ci.org/obspy/obspy/jobs/216730989#L1482) to not change main dependency versions:
```
$ conda install --no-update-dependencies cartopy || true
Fetching package metadata ...........
Solving package specifications: .
Package plan for installation in environment /Users/travis/miniconda/envs/test-environment:
The following NEW packages will be INSTALLED:
    cartopy: 0.14.3-np110py27_3 conda-forge
    jpeg:    9b-0               conda-forge
    libtiff: 4.0.6-7            conda-forge
    owslib:  0.14.0-py27_0      conda-forge
    pillow:  3.2.0-py27_1       conda-forge
    proj4:   4.9.3-3            conda-forge
    pyepsg:  0.3.1-py27_0       conda-forge
    pyshp:   1.2.10-py27_0      conda-forge
    shapely: 1.5.16-py27_0                 
```

---

I checked locally, `--no-update-dependencies` does show an error if it can not accomodate those installed package versions that it's not able to change, so I think our way of installing optional deps should work..
```
$ conda install --no-update-dependencies cartopy=0.14.3
Fetching package metadata ...........
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - cartopy 0.14.3*
  - libgdal 2.1.0 0
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by ocefpaf** [comment]
That is an old build and not even the last build number in that version series. Any special reason to use that?

If you really need version `0.14.3` try to get the build number `4`. conda solver has the bad habit of easing into bad mix of pinning by installing old build numbers. (That is, IMO, a bug in conda and lower build number should never be installed unless explicitly requested.)

**Comment by ocefpaf** [comment]
BTW build number `4` was pinned to  `geos 3.5.*` and `3` used  `geos 3.4.*`. So there is no way either will work with `geos 3.3.3` that conda is installing there. See https://github.com/conda-forge/cartopy-feedstock/commit/294bb42dd692c971710eb3b864070ad18911d3e9

Not sure why you are getting `geos 3.3.3`. Maybe you are hitting http://conda-forge.github.io/docs/conda-forge_gotchas.html#using-multiple-channels or maybe your config is force installing it. Either way that won't work. Closing this as there is nothing we can do... Sorry.

**Comment by megies** [comment]
Hmm.. indeed it should install a newer cartopy package.. strange.. need to investigat why it's trying to install that old package/build..
