### ISSUE TITLE
problem with goes_c library in Cartopy

### ISSUE THREAD

**Issue by mcFishin2039** [conda-forge/cartopy-feedstock#38]
Hi, 

I am using Anaconda with python 2.7 on a mac OS  and I installed the package Cartopy. 

However, I notice that when I attempt to use Cartopy (import cartopy), I obtain the following error: 

OSError: Could not find lib geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib'].

Now, I've found where this library lives, it's in the path:
/Users/ramosmd/anaconda/lib/libgeos_c.dylib

How do I tell Anaconda to look here for the geos_c library? I've attempted upgrading cartopy and all its dependencies, but it just can't link to the library. 

I saw someone had a similar issue from the mac side for this library, and I saw the ticket was closed and there was no resolution on this issue. Any help is appreciated greatly!!! 

Best, 

Marlon

**Comment by ocefpaf** [comment]
Please take a look at https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels 

Are you installing `cartopy` in the root env? If so can you try it installing it in an env?

```shell
conda create --name TEST python=2.7 cartopy --yes
source activate TEST
python -c "import cartopy; print(cartopy.__version__)"
```

**Comment by mcFishin2039** [comment]
Hi ! 

When I installed it in a separate environment, it did the trick! It was able to find all the libraries it needed. Thanks so much!

**Comment by ocefpaf** [comment]
Glad it helped! Closing this.
