### ISSUE TITLE
PIL Packaging Bug

### ISSUE THREAD

**Issue by DominicAntonacci** [conda-forge/cartopy-feedstock#42]
With a vanilla Anaconda python 3.6 distribution on Windows 7, the following install command clobbers something in the PIL module. 
```
conda install -c conda-forge cartopy
```

When trying to import `cartopy.io.img_tiles`, an import error then occurs.
```python
import cartopy.io.img_tiles
Traceback (most recent call last):

  File "<ipython-input-106-feb3ede8296d>", line 1, in <module>
    import cartopy.io.img_tiles

  File "C:\Anaconda3\lib\site-packages\cartopy\io\img_tiles.py", line 32, in <module>
    from PIL import Image

  File "C:\Anaconda3\lib\site-packages\PIL\Image.py", line 56, in <module>
    from . import _imaging as core

ImportError: DLL load failed: The specified module could not be found.
```

This can be fixed with `conda upgrade -c conda-forge pillow` or `conda config --add channels conda-forge`, depending if you want to add a channel or not.

I suspect cartopy is expecting pillow 4.3.0 (conda-forge), not 4.2.1 (standard conda)

**Comment by ocefpaf** [comment]
Indeed `cartopy` is installing `pillow`. I don't think you can use it with `PIL`. If you need PIL for other projects you'll need to create separate envs.
