### ISSUE TITLE
Cartopy crashes (again?) on OSX

### ISSUE THREAD

**Issue by andreww** [conda-forge/cartopy-feedstock#44]
I'm running into a problem that looks very like a reappearance of the error described in #36 but with, I think, the latest versions of cartopy and shapely. I would be grateful if somebody could take a quick look and let me know if it looks like I'm doing something silly.

The specific error that I'm seeing is that importing cartopy results in an error message and the python interpreter crashes:

    Python 3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:25:17) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import cartopy
    Invalid argument (must be a Polygon)
    Geometry must be a Point or LineString
    Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3991.
    Abort trap: 6

I have a version of `geos` installed via homebrew and removing this makes this crash go away. However, I more-or-less need that external version of geos because one of the things the python code I'm running does is drive a legacy Fortran application. To compile that I need `gmt4`, and this needs `geos`... 

The other potential workaround in #36 is to downgrade `shapely` to `1.5.17`. I've tried this too but end up with a different error:

    Python 3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:25:17) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import cartopy
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "//anaconda/envs/lema-foe/lib/python3.6/site-packages/cartopy/__init__.py", line 111, in 
    <module>
        import cartopy.feature
      File "//anaconda/envs/lema-foe/lib/python3.6/site-packages/cartopy/feature.py", line 32, in 
    <module>
        import cartopy.io.shapereader as shapereader
      File "//anaconda/envs/lema-foe/lib/python3.6/site-packages/cartopy/io/shapereader.py", line 52, in <module>
        import shapefile
    ModuleNotFoundError: No module named 'shapefile'

I think this is because the downgrade leaves me with the wrong version of `pyshp`, but I've not been able to find a more useful older version. Any suggestions?

Some more information on my environment. Output from `conda list`:

    # packages in environment at //anaconda/envs/lema-foe:
    #
    appnope                   0.1.0                    py36_0  
    astropy                   2.0.2            py36h4654939_4  
    bleach                    1.5.0                    py36_0  
    cartopy                   0.16.0                   py36_0    conda-forge
    cycler                    0.10.0                   py36_0  
    decorator                 4.0.11                   py36_0  
    entrypoints               0.2.2                    py36_1  
    freetype                  2.5.5                         2  
    geos                      3.6.2                hfc679d8_2    conda-forge
    hdf5                      1.8.17                        1  
    healpy                    1.11.0                   py36_1    conda-forge
    html5lib                  0.999                    py36_0  
    icu                       54.1                          0  
    ipykernel                 4.6.1                    py36_0  
    ipython                   6.0.0                    py36_0  
    ipython_genutils          0.2.0                    py36_0  
    ipywidgets                6.0.0                    py36_0  
    jbig                      2.1                           0  
    jinja2                    2.9.6                    py36_0  
    jpeg                      9b                            0  
    jsonschema                2.6.0                    py36_0  
    jupyter                   1.0.0                    py36_3  
    jupyter_client            5.0.1                    py36_0  
    jupyter_console           5.1.0                    py36_0  
    jupyter_core              4.3.0                    py36_0  
    libiconv                  1.14                          0  
    libpng                    1.6.27                        0  
    libtiff                   4.0.6                         3  
    libxml2                   2.9.4                         0  
    libxslt                   1.1.29                        0  
    llvmlite                  0.20.0                   py36_0  
    lxml                      3.8.0                    py36_0  
    markupsafe                0.23                     py36_2  
    matplotlib                2.0.0               np112py36_0  
    mistune                   0.7.4                    py36_0  
    mkl                       2017.0.1                      0  
    nbconvert                 5.1.1                    py36_0  
    nbformat                  4.3.0                    py36_0  
    nose                      1.3.7                    py36_1  
    notebook                  5.0.0                    py36_0  
    numba                     0.35.0              np112py36_0  
    numexpr                   2.6.2               np112py36_0  
    numpy                     1.12.1                   py36_0  
    olefile                   0.44                     py36_0  
    openssl                   1.0.2k                        1  
    owslib                    0.16.0                     py_0    conda-forge
    pandocfilters             1.4.1                    py36_0  
    path.py                   10.3.1                   py36_0  
    pexpect                   4.2.1                    py36_0  
    pickleshare               0.7.4                    py36_0  
    pillow                    4.2.1                    py36_0  
    pip                       9.0.1                    py36_1  
    proj4                     4.9.3                         5    conda-forge
    prompt_toolkit            1.0.14                   py36_0  
    ptyprocess                0.5.1                    py36_0  
    py                        1.4.34                   py36_0  
    pyepsg                    0.3.2                    py36_0    conda-forge
    pygments                  2.2.0                    py36_0  
    pyparsing                 2.1.4                    py36_0  
    pyproj                    1.9.5.1                  py36_0  
    pyqt                      5.6.0                    py36_2  
    pyshp                     1.2.12                     py_0    conda-forge
    pytables                  3.3.0               np112py36_0  
    pytest                    3.2.1                    py36_0  
    pytest-runner             2.11.1                   py36_0  
    python                    3.6.1                         0  
    python-dateutil           2.6.0                    py36_0  
    pytz                      2017.2                   py36_0  
    pyyaml                    3.12                     py36_0  
    pyzmq                     16.0.2                   py36_0  
    qt                        5.6.2                         0  
    qtconsole                 4.3.0                    py36_0  
    readline                  6.2                           2  
    requests                  2.14.2                   py36_0  
    scipy                     0.19.0              np112py36_0  
    setuptools                27.2.0                   py36_0  
    shapely                   1.6.4            py36h164cb2d_1    conda-forge
    simplegeneric             0.8.1                    py36_1  
    sip                       4.18                     py36_0  
    six                       1.10.0                   py36_0  
    sqlite                    3.13.0                        0  
    terminado                 0.6                      py36_0  
    testpath                  0.3                      py36_0  
    tk                        8.5.18                        0  
    tornado                   4.5.1                    py36_0  
    traitlets                 4.3.2                    py36_0  
    wcwidth                   0.1.7                    py36_0   
    wheel                     0.29.0                   py36_0  
    widgetsnbextension        2.0.0                    py36_0  
    xz                        5.2.2                         1  
    yaml                      0.1.6                         0  
    zlib                      1.2.8                         3

Output from `conda info`:

    Current conda install:

               platform : osx-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 1.8.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : //anaconda  (writable)
    default environment : //anaconda/envs/lema-foe
       envs directories : //anaconda/envs
          package cache : //anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /Users/earawa/.condarc
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.4 CPython/2.7.12 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 502:20

**Comment by ocefpaf** [comment]
There are many many from `defaults` there which suggests you may be hitting a channel mix problem. Please https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels for more info and recommend practices.

I just tested a fresh env with:

```shell
conda create --name TEST python=3.6 cartopy
conda activate TEST
python -c 'import cartopy; print(cartopy.__version__)'
0.16.0
```

and everything worked as expected.
