### ISSUE TITLE
PROJ 6.1.1 builds for Windows failed

### ISSUE THREAD

**Issue by djhoese** [conda-forge/cartopy-feedstock#68]
Looking at https://anaconda.org/conda-forge/cartopy/files and the README for appveyor/azure builds, it looks like the win64 builds where cartopy was built against PROJ 6.1.1 failed and no win64 package is available (from the builds that were 12 days ago).

Looking at appveyor it looks like an environment variable wasn't set to use the old PROJ API. Let me know if I'm missing something.

**Comment by ocefpaf** [comment]
> Looking at appveyor it looks like an environment variable wasn't set to use the old PROJ API. Let me know if I'm missing something.

Yep. That is correct. We tried without avail to make that work with cartopy, including some patching. Nothing worked. We decided to merge to "cash" Linux and OS X and wait for upstream to fix the situation.

**Comment by ocefpaf** [comment]
xref.: https://github.com/conda-forge/cartopy-feedstock/pull/64#issuecomment-510684142

**Comment by ocefpaf** [comment]
Thanks @dopplershift for fixing this in #70.
