### ISSUE TITLE
Cannot install cartopy on Python 3.8 version via conda-forge

### ISSUE THREAD

**Issue by krishnaap** [conda-forge/cartopy-feedstock#83]
When I tried to install cartopy with python 3.8 and spyder 4.1.2, it is showing the error

    UnsatisfiableError: The following specifications were found
    to be incompatible with the existing python installation in your environment:

    cartopy -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

**Comment by ocefpaf** [comment]
@krishnaap please fill all the information required in the issue template, otherwise we cannot help you. I'm closing this so you can open a new one with required info.
